[build]
  # Skips the build step since this is a static HTML/CSS/JS site.
  command = "echo 'No build command needed'"
  # Specifies that the files in the root directory should be published.
  publish = "."

# This section prevents Netlify from trying to render a page for
# files that might be missing, ensuring the site doesn't 404.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
